DROP TABLE IF EXISTS Votes CASCADE;
DROP TABLE IF EXISTS Posts CASCADE;
DROP TABLE IF EXISTS Users CASCADE;

CREATE TABLE IF NOT EXISTS Users
(
  id          SERIAL PRIMARY KEY,
  username    VARCHAR(100),
  hashedPass  CHAR(60)
);

CREATE TABLE IF NOT EXISTS Posts
(
  id          SERIAL        PRIMARY KEY,
  masterPost  BIGINT        UNSIGNED,
  parentPost  BIGINT        UNSIGNED,
  title       VARCHAR(100)  NOT NULL,
  url         VARCHAR(2083),
  text        VARCHAR(500),
  timestamp   BIGINT,
  owner       BIGINT        UNSIGNED,
  FOREIGN KEY(owner)        REFERENCES Users(id) ON DELETE CASCADE
);

ALTER TABLE Posts ADD FOREIGN KEY (masterPost) REFERENCES Posts(id) ON DELETE CASCADE;
ALTER TABLE Posts ADD FOREIGN KEY (parentPost) REFERENCES Posts(id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS Votes
(
  userID      BIGINT        UNSIGNED,
  postID      BIGINT        UNSIGNED,
  vote        TINYINT,
  PRIMARY KEY(userID,postID),
  FOREIGN KEY(userID)       REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY(postID)       REFERENCES Posts(id) ON DELETE CASCADE
);
